### ISSUE TITLE
support append for memory region

### ISSUE THREAD

**Issue by my-vegetable-has-exploded** [datenlord/async-rdma#109]
async-rdma memory region need to use with lock_utilities::MappedRwLockReadGuard.
```rust
lmr.as_mut_slice().write(&[1_u8; 8])
```
I want to append(this can be done by wrapping with std::io::cursor) some bytes to mr to avoid useless copy.

But we can't build a cursor with (MappedRwLockReadGuard<T>), like
```rust
    let cursor = std::io::Cursor::new(lmr.as_mut_slice());
	cursor.write(&[1_u8; 8])?;
```

so, i think we can consider providing a MappedRwLockWriteGuard<Cursor<&mut [u8]>>. 

If needed, i can open a pr to add it.

**Comment by GTwhy** [comment]
Hi @my-vegetable-has-exploded , `lmr.as_mut_slice()` will return a `MappedRwLockWriteGuard` but not a `MappedRwLockReadGuard`. Do You mean the `cursor` you get by `std::io::Cursor::new(lmr.as_mut_slice())` has a type of `Cursor<MappedRwLockWriteGuard<&mut [u8]>>`, which is not able to write, so you want to add an API to return a `MappedRwLockWriteGuard<Cursor<&mut [u8]>>`?

**Comment by my-vegetable-has-exploded** [comment]
yes
In this way, we can provide a convenient way for users to append to lmr without having to manage the cursor themselves.

**Comment by GTwhy** [comment]
@my-vegetable-has-exploded OK，welcome to open the PR!
