### ISSUE TITLE
confusion about support for Infiniband and mlx5?

### ISSUE THREAD

**Issue by fishiu** [datenlord/async-rdma#119]
(First I have to declare that I am really a novice to RDMA ...)

This library works pretty fine when I am playing RDMA based on **SoftiWARP**. However now when I am trying to apply all my code and tool to a platform equipped with the **MLX5** card, I failed to connect my rdma server and client (by specifying ip:port) anymore.

Sorry that this question might be stupid but I am not quite clear about the relationship and difference between these concepts: RoCE, RXE, iWARP, MLX, Infiniband(IB) ...

Does this repo only support RoCE but not Infiniband(IB)?

**Comment by GTwhy** [comment]
Hi, @fishiu 
I guess you used the default config to build the the `Rdma` instance?
Maybe you should set the dev_name, port_num and sgid_index that are device related.

The related fn is `Context::open`, you can check it.

**Comment by fishiu** [comment]
@GTwhy Thanks so much, I have figured out the problem which is indeed caused by dynamic linking that makes the devices invisible.

Anyway I am still not very clear about this question, could you please give a simple answer (conclusion) that what RDMA protocols does this repo support?

**Comment by GTwhy** [comment]
> @GTwhy Thanks so much, I have figured out the problem which is indeed caused by dynamic linking that makes the devices invisible.
> 
> Anyway I am still not very clear about this question, could you please give a simple answer (conclusion) that what RDMA protocols does this repo support?

This repo support RC, and whatever the underlying implementation is.
Here is a great column that can help you understand concepts.
https://zhuanlan.zhihu.com/p/164908617

**Comment by fishiu** [comment]
Thanks for your reply, I will loop deep into it!
