### ISSUE TITLE
Claiming the name on crates.io?

### ISSUE THREAD

**Issue by minghuaw** [datenlord/async-rdma#21]
There have been some "bad actors" who falsely claim names of successful projects on crates.io. It seems like datenlord hasn't really published any work on crates.io yet. This leaves the room for the "bad actors". Would you consider publish this crate or even just claim the name first?

**Comment by rogercloud** [comment]
Thanks for the advice. Actually we're on the state of ready for releasing, we'll publish it as soon as possible when a version is ready.

**Comment by rogercloud** [comment]
We've publish a version on crates.io https://crates.io/crates/async-rdma
