### ISSUE TITLE
Cancellation safety

### ISSUE THREAD

**Issue by Nugine** [datenlord/async-rdma#47]
Disclaimer: I know nothing about the details of RDMA before.

I have some questions about the example at first glance.

<https://github.com/datenlord/async-rdma/blob/2a55f3261b1b9820f8e6f4b2e80086eafb8d328b/examples/rpc.rs#L44-L57>

1. When will the local memory region be deallocated?
2. Does the unsafe statement have any safety requirements?
3. What if the future returned by `sync_with_client` is dropped (cancelled) before the request completes?

Related article: https://zhuanlan.zhihu.com/p/346219893

**Comment by GTwhy** [comment]
Hi, thanks for your thoughtful questions and article.

1. For now, the relationship between LocalMr and RawMemoryRegion(contains ibv_mr : the "real" RDMA memory region) is one-to-one, and they are connected through Arc . So the memory region drop flow is : lmr.drop() -> raw_mr.drop() -> ibv_dreg_mr(ibv_mr). It's simple but inefficient, so we will transform jemalloc to manage ibv_mr  and reuse it's preapplication and retain strategy in the next release.

2. The operations in the unsafe statement here almost degenerate to operations on raw memory pointers in C. I haven't thought carefully about how to pack this part better. I saw in the article that you have some thoughts about this. Maybe you have good ideas.

3. Good question! That's depending on the stage of the request. If the future dropped before or after `ibv_post_send`(rdma api) done, there will only be some error messages. But the handling of this during the execution of `ibv_post_send` has not been taken into account. This question is similar to the one mentioned in your article. 

I will deal with the above issues later. You are welcome to contribute if you are interested, Thank you!
