### ISSUE TITLE
Unnecessary overflow check

### ISSUE THREAD

**Issue by Nugine** [datenlord/async-rdma#53]
`left.overflow_shl(32)` never panics because `0 <= time < 1e6`. It can be written as `left.wrapping_shl(32)`.

https://github.com/datenlord/async-rdma/blob/2a55f3261b1b9820f8e6f4b2e80086eafb8d328b/src/id.rs#L5-L20

`self.addr().overflow_add(i.start)` and `i.end.overflow_sub(i.start)` never panic because the bounds have been checked.

(Should `"wrong range of lmr"` be an IO error?)

https://github.com/datenlord/async-rdma/blob/2a55f3261b1b9820f8e6f4b2e80086eafb8d328b/src/memory_region/local.rs#L84-L112

https://github.com/datenlord/async-rdma/blob/ef9c48d58237a4393cec71c10cc1511142d52a57/src/memory_region/remote.rs#L62-L92

`start.overflow_add(self.max_sr_data_len)` can be writtern as `start.saturating_add(self.max_sr_data_len)`

`end.overflow_sub(start)` never panics because `start < end`.

https://github.com/datenlord/async-rdma/blob/2441414ddda146ef3484eae0523b13e14946f09a/src/agent.rs#L175-L178

**Comment by rogercloud** [comment]
@Nugine 
1. Thanks for the overflow checking advice, we'll walk through it later.
2. As it's an I/O lib, we generally wrap all errors into I/O error, in that way it's easy to manage the error type. Do you have any advice or better practice?

**Comment by Nugine** [comment]
@rogercloud 

> As it's an I/O lib, we generally wrap all errors into I/O error

Since "out of bounds" can not describe the actual error in most cases, `{Local|Remote}Mr::get[_mut]` should return option types or simply panic. 
For high performance, the memory region should provide unsafe getters like `get_unchecked[_mut]`  to avoid unnecessary bounds checks.

**Comment by rogercloud** [comment]
"Return option type" is really a better choice, None means "out of bounds" in this case.
Actually it's a high level lib for RMDA, we don't want to expose any unsafe API outside.

**Comment by Nugine** [comment]
> Actually it's a high level lib for RMDA, we don't want to expose any unsafe API outside.

Unsafe API does not mean "low-level", but means "use it carefully if you want higher performance".
