### ISSUE TITLE
Potential unsoundness

### ISSUE THREAD

**Issue by Nugine** [datenlord/async-rdma#54]
There is no guarantee that the safety requirements are met here.

<https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html#safety>

https://github.com/datenlord/async-rdma/blob/97fad332e72c83eaaaef3fef997b64a3aa932da8/src/memory_region/local.rs#L15-L19

https://github.com/datenlord/async-rdma/blob/97fad332e72c83eaaaef3fef997b64a3aa932da8/src/memory_region/local.rs#L34-L38

**Comment by Nugine** [comment]
Alignment mismatch

```rust
#[test]
fn align_check() {
    use std::mem::align_of;
    assert_eq!(align_of::<Gid>(), align_of::<ibv_gid>());
}
```

```
running 1 test
thread 'gid::align_check' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `8`', src/gid.rs:68:5
```

https://github.com/datenlord/async-rdma/blob/9a32a81bcc87c346a7033e8dc5d83a8023b8cbdb/src/gid.rs#L45-L63

**Comment by rogercloud** [comment]
> There is no guarantee that the safety requirements are met here.
> 
> https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html#safety
> 
> https://github.com/datenlord/async-rdma/blob/97fad332e72c83eaaaef3fef997b64a3aa932da8/src/memory_region/local.rs#L15-L19
> 
> https://github.com/datenlord/async-rdma/blob/97fad332e72c83eaaaef3fef997b64a3aa932da8/src/memory_region/local.rs#L34-L38

These two trait are crate pub traits, the usage is limited in the crates, so the discussion boundry is limited.

Safety cares the following points:
1. The memory is aligned properly and the memory region is available for read. The alignment of `u8` is natrually met, and the read permission is garanteed in all the implementations.
2. The content is properly initialized, for `u8` type the requirement is meaningless, any value is valid.
3. The mutation property is considered, we can only get one mutable reference. The property is guarded by the Rust compiler.
4. The length of the memory region should not exceed `isize::MAX`. We're not checking it correctly. *It's a good catch*

**Comment by rogercloud** [comment]
> Alignment mismatch
> 
> ```rust
> #[test]
> fn align_check() {
>     use std::mem::align_of;
>     assert_eq!(align_of::<Gid>(), align_of::<ibv_gid>());
> }
> ```
> 
> ```
> running 1 test
> thread 'gid::align_check' panicked at 'assertion failed: `(left == right)`
>   left: `1`,
>  right: `8`', src/gid.rs:68:5
> ```
> 
> https://github.com/datenlord/async-rdma/blob/9a32a81bcc87c346a7033e8dc5d83a8023b8cbdb/src/gid.rs#L45-L63

It's a good catch. We'll add more alignment constrain on `Gid` struct.

**Comment by Nugine** [comment]
@rogercloud 

> These two trait are crate pub traits, the usage is limited in the crates,

The traits are parts of the public api in v0.2.0. They should be marked as **sealed traits** or **unsafe traits**.

https://docs.rs/async-rdma/0.2.0/async_rdma/index.html#traits

> The content is properly initialized, for u8 type the requirement is meaningless, any value is valid.

The trait itself can not ensure this. Even raw bytes must be initialized before reading.

Example:
Click `Tools` -> `Miri`, it reports undefined behavior.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=5d09005a17d00ab33ff9d86ce8844de6

> the memory region is available for read

The `as_ptr` method in the trait does not ensure that the returned pointer is valid.

**Comment by rogercloud** [comment]
@Nugine

I think we should mark the trait as **sealed traits**, so that they can't be implemented by the users.

For `u8` type initialization means setting zero, which is inefficient for a large memory block. Let's provide two types of APIs, one for fast and unsafe requirements, the other for zeroed and safe requirements.

**Comment by Nugine** [comment]
@rogercloud 

What about **sealed unsafe traits**?

**Comment by rogercloud** [comment]
> 

Yes off cource, if it contains unsafe interface, it's unsafe.

**Comment by Nugine** [comment]
Exporting uninitialized memory
https://github.com/datenlord/async-rdma/pull/49#discussion_r855033949
https://github.com/datenlord/async-rdma/blob/ab99fa389e3e8540e0153109fca625ea565a708c/src/mr_allocator.rs#L108-L132
