### ISSUE TITLE
Avoid unnecessary overflow checking operations

### ISSUE THREAD

**Issue by rogercloud** [datenlord/async-rdma#57]
We use overflow checking operations in almost all situations, which is performance unfriendly. We need to work through the code base to avoid the unnecessary ones. #53

**Comment by Nugine** [comment]
Just search the usages of `clippy_utilities::OverflowArithmetic` (regex `\.overflow_*`). 
I'm sure that all of them can be replaced.

**Comment by rogercloud** [comment]
I'm not sure to replace all of them, some of the overflow checkings are necessary. Let's go through them one by one.
