### ISSUE TITLE
Support working with existing apps

### ISSUE THREAD

**Issue by wangrunji0408** [datenlord/async-rdma#75]
The current implementation defines its own protocol to establish connections and send/receive messages. This brings a limitation that both client and server must use this library to communicate. We can not use this library to build a client of an existing rdma server. So I have 2 suggestions that might help:
1. Support setting up connections through RDMA CM.
2. Add lower-level APIs to send/receive raw messages.

**Comment by GTwhy** [comment]
Agree with your advices.
The compatibility with existing RDMA apps has not been considered in the current implementation and I'm going to try.

**Comment by GTwhy** [comment]
@wangrunji0408  Hi, we add some APIs for RDMA CM and send/recv raw data in #78 , but I forget ref this issue in commit message. 
Here is an [example](https://github.com/datenlord/async-rdma/blob/master/examples/cm_client.rs).
