### ISSUE TITLE
How many types of rdma network cards does async-rdma support?

### ISSUE THREAD

**Issue by dragon-zhang** [datenlord/async-rdma#86]
Such as, `InfiniBand` card, `RoCE` card and `iWARP` card.

**Comment by GTwhy** [comment]
We build async-rdma based on Verbs APIs which can be used to drive many types of cards.

Of course different cards has different features, we mainly support RoCE for now, and support for other types of cards is also welcome.

We tested this lib on Soft-RoCE and the hardware card that supports RoCE v1&v2.

What kind of card do you need to use?

**Comment by GTwhy** [comment]
> Such as, `InfiniBand` card, `RoCE` card and `iWARP` card.

Hi! We build async-rdma based on Verbs APIs which can be used to drive many types of cards.

Of course different cards has different features, we mainly support RoCE for now, and support for other types of cards is also welcome.

We tested this lib on Soft-RoCE and the hardware card that supports RoCE v1&v2.

What kind of card do you need to use?

**Comment by dragon-zhang** [comment]
RoCE v2, and thanks for your help.



发自我的iPhone


------------------ Original ------------------
From: 王恒宇 ***@***.***&gt;
Date: Sun,Oct 30,2022 6:02 PM
To: datenlord/async-rdma ***@***.***&gt;
Cc: dragon-zhang ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [datenlord/async-rdma] How many types of rdma network cards does async-rdma support? (Issue #86)





  
Such as, InfiniBand card, RoCE card and iWARP card.
  
Hi! We build async-rdma based on Verbs APIs which can be used to drive many types of cards.
 
Of course different cards has different features, we mainly support RoCE for now, and support for other types of cards is also welcome.
 
We tested this lib on Soft-RoCE and the hardware card that supports RoCE v1&amp;v2.
 
What kind of card do you need to use?
