### ISSUE TITLE
Encounter a doubt when using MR in async-rdma

### ISSUE THREAD

**Issue by mond77** [datenlord/async-rdma#95]
In studying this library, the following result were encountered. And I was confused about that.
request structure:
<img width="396" alt="Screenshot 2023-03-01 at 22 48 29" src="https://user-images.githubusercontent.com/82888636/222174695-4a5266b3-63ab-41b2-abeb-91ef5c0833dd.png">
client side:
<img width="984" alt="Screenshot 2023-03-01 at 22 48 37" src="https://user-images.githubusercontent.com/82888636/222174860-3be2d2e2-9630-4a8a-aa1e-db7618f8fa4e.png">
server side:
<img width="775" alt="Screenshot 2023-03-01 at 22 48 58" src="https://user-images.githubusercontent.com/82888636/222174875-c61f5020-348f-49da-9f96-667a69b7d95f.png">
main:
<img width="984" alt="Screenshot 2023-03-01 at 22 48 20" src="https://user-images.githubusercontent.com/82888636/222174814-13182f97-d3be-491c-8bca-9d029a274ec4.png">
result: 
```
rpc server started
header size: 28
size: 80, 
Msg { header: RequestHeader { id: 0, type: 0, flags: 0, total_length: 0, file_path_length: 0, meta_data_length: 0, data_length: 0 }, meta_data: [], data: [] }
server side size: 80, 
Msg { header: RequestHeader { id: 0, type: 0, flags: 0, total_length: 6, file_path_length: 0, meta_data_length: 3, data_length: 3 }, meta_data: [1, 2, 3, 4, 5], data: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2] }
response: Msg { header: ResponseHeader { id: 0, status: 0, flags: 0, total_length: 0, meta_data_length: 0, data_length: 0 }, meta_data: [1, 2, 3, 4, 5], data: [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4] }
```

**Comment by mond77** [comment]
Doubt solved. I was careless and didn't pay attention to the localhost communication problem. After switching to remote communication, Segmentation fault is reported.

**Comment by GTwhy** [comment]
Hi, We can communicate at [gitter](https://app.gitter.im/#/room/#datenlord_async-rdma:gitter.im) or [discussions](https://github.com/datenlord/async-rdma/discussions)

> I am developing with this library, do you have an open source developer group chat? Can I participate in it?

**Comment by mond77** [comment]
In examples/rpc.rs the type of data transferred is String that might misguide users. The data pointed to by String is not actually transferred. Is there a solution for transferring data of variable length in async-rdma?

**Comment by GTwhy** [comment]
> In examples/rpc.rs the type of data transferred is String that might misguide users. The data pointed to by String is not actually transferred. Is there a solution for transferring data of variable length in async-rdma?

Yes you are right! This is a misleading example written in the early stage, we should serialize and deserialize the messages.
Maybe you can make this change if you are interested.

You can use API `write_with_imm` to write data with a number(length of the data), and do some type conversion unsafely if you want to avoid serialization & deserialization. Here is an [example](https://github.com/datenlord/async-rdma/blob/d5656e3160f2d6c4b4e03b3671894e7c80613e29/examples/server.rs#L61)

**Comment by mond77** [comment]
> > In examples/rpc.rs the type of data transferred is String that might misguide users. The data pointed to by String is not actually transferred. Is there a solution for transferring data of variable length in async-rdma?
> 
> Yes you are right! This is a misleading example written in the early stage, we should serialize and deserialize the messages. Maybe you can make this change if you are interested.
> 
> You can use API `write_with_imm` to write data with a number(length of the data), and do some type conversion unsafely if you want to avoid serialization & deserialization. Here is an [example](https://github.com/datenlord/async-rdma/blob/d5656e3160f2d6c4b4e03b3671894e7c80613e29/examples/server.rs#L61)

How could the serialized and deserialized messages of uncertain size  be transferred in RDMA? That we even don't know how much memory to allocate. Maybe the simplest example should be like the pr above.

**Comment by GTwhy** [comment]
Currently, we can only request a fixed size memory region, which cannot adapt well to dynamically changing data structures. Usually, it may be necessary to pre-allocate a larger block of memory and send additional metadata to notify the remote end of the data changes. Thanks for your PR!

**Comment by mond77** [comment]
Yeah, dynamic data structures need special design to handle. async-rdma gives a good reference for developers who write RDMA programs in rust, and I learned a lot from it and still learning it. Nice job！
