### ISSUE TITLE
Connection timeout between servers

### ISSUE THREAD

**Issue by cholcombe973** [datenlord/async-rdma#99]
I'm new to RDMA in general so I'm just trying to explore how this works. I tried the `cargo run --example rpc` on my localhost and it runs fine. However when I try to run this between 2 servers I get a timeout error once the client connects. I'm using the `cargo run --example client` and `cargo run --example server`. Any troubleshooting tips?

**Comment by GTwhy** [comment]
Hi! The server and client exmaple was made for localhost test. So the address and port number is hard-coded in the code and you need to change it based on the specific information of your two servers in the server.rs and client.rs. 

That is not a good practice and getting parameters from the command line is a better choice. I will update the server & client example later. Thanks for the feedback!

**Comment by cholcombe973** [comment]
Sure no problem. I actually edited the ip addresses by hand in the code but I agree that taking command line parameters would be better.

**Comment by GTwhy** [comment]
It seems that this issue has been resolved, so I will close it. Feel free to reopen it if you have any other questions~
